name: CI to Docker Hub
on:
  push:
    branches: [ master ]
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 9,9 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v1
      - name: Login to GitHub Package Registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login docker.pkg.github.com -u "${{ secrets.DOCKER_USER }}" --password-stdin

      - uses: docker/build-push-action@v2
      - name: Build and push
        run: buildx build --tag "${{ secrets.DOCKER_USER }}"/webserver:latest --iidfile /tmp/docker-build-push-xmfueb/iidfile --file ./Dockerfile --push .

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
