name: CI to Docker Hub
on:
  push:
    branches: [ master ]
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 9,9 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v1
      - name: Login to GitHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

      - name: Build and push
        run: docker buildx build --tag "${{ secrets.DOCKER_USER }}"/webserver --file ./Dockerfile --push .

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
